### ISSUE TITLE
Remove all unnecessary comments

### ISSUE THREAD

**Issue by gaal1le0** [ManuuMT/Traffic-Light-React#2]
https://github.com/ManuuMT/Traffic-Light-React/blob/a42ff2210c36aaa3f539c743be21083cda1ffd29/src/js/index.js#L1

Please try to keep in mind that unnecessary comment are not needed here, it obvious that the following sentence import a component, please remove all these comments from all the files of your projects, it's a really big mistake to send code with a lot of comments that are not needed. Only you need to comment code that can bring some misunderstandings :) 

```js
import Home from '../home.jsx'
```

PD: Please remove all the code, and close the issue, later send via BreathCode the assignment.

**Comment by AlterManu** [comment]
All unnecessary comments were deleted.
